#!/usr/bin/env python3

# -*- coding: utf-8 -*-
import re
import sys
import argparse
import os
import pwd

from jupyter_core.command import main

if __name__ == '__main__':
    my_uid = os.getuid()
    my_name = pwd.getpwuid(my_uid).pw_name
    my_args = ["notebook", "--no-browser", "--ip", "localhost", "--port",
               "{port}".format(port=my_uid),
               "--ip", "*",
               "--notebook-dir", os.path.join("/share","data", my_name)]
    sys.argv = [sys.argv[0]] + my_args
    sys.exit(main())
